### ISSUE TITLE
Undefined subroutine &CFG::remove_root

### ISSUE THREAD

**Issue by xloem** [vaeth/find_cruft#1]
```
~/src/find_cruft/bin $ ./find_cruft -c ../etc/ /lib64
Undefined subroutine &CFG::remove_root called at ./find_cruft line 723.
~/src/find_cruft/bin $
```

**Comment by vaeth** [comment]
The option -c ../etc/ does not do what you expect: You probably mean -c ../etc/find_cruft.pl
With the latter, there is no problem.
The error message occurs only if there is no config file at all - a situation in which find_cruft is not meant to be used and which was never tested.
Anyway, find_cruft shouldn't crash in this exceptional situation: This is fixed in v3.0.9.
